// Generated by https://quicktype.io

export interface CastDetail {
    id:          number;
    name:        string;
    gender:      string;
    tmdbUrl:     string;
    profilePath: string;
    movies:      Movie[];
}

export interface Movie {
    id:        number;
    title:     string;
    posterUrl: string;
    character: string;
    revenue:   number;
    rating:    number;
}
